[package]
name = "io-replica"
description = "Offline-first replica engine library for Rust"
version = "0.5.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.87"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "no-std"]
keywords = ["io-free", "no-std", "coroutine", "offline", "sync"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/io-replica/latest/io_replica"
repository = "https://github.com/pimalaya/io-replica"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "mailbox_lifecycle"
path = "examples/mailbox_lifecycle.rs"

[dev-dependencies]
proptest = { version = "1", default-features = false, features = ["std"] }

[dependencies]
log = { version = "0.4", default-features = false }
thiserror = { version = "2", default-features = false }
